name: Node.js CI

on:
    push:
        branches:
            - dev
        tags-ignore:
            - v*
    pull_request:
        branches:
            - main
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install pnpm
              run: npm install -g pnpm@latest
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Build
              run: pnpm run build --if-present
            - name: Linting
              run: pnpm run lint:check
            - name: Tests
              run: pnpm test
