name: Node.js CI

on:
    push:
        branches:
          - main
          - dev
        tags-ignore:
          - v*
    pull_request:
        branches:
          - main
          - dev

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - run: npm run build --if-present
            - run: npm run lint
            - run: npm test
